-- Lua 5.2 opcode exercise file
--
-- This script attempts to exercise most of the opcodes present in Lua 5.2.
-- It is based on similar work done for Lua 5.1 but adapted for the
-- changes introduced in the 5.2 VM.  In particular Lua 5.2 removes
-- `GETGLOBAL` and `SETGLOBAL` and instead accesses globals through
-- the `_ENV` upvalue, and introduces the new `LOADKX`/`EXTRAARG`
-- pair.  The code below covers loads, stores, arithmetic, comparison,
-- control‑flow, calls, closures, varargs and table operations.  It
-- intentionally uses simple constructs to provoke the bytecode
-- generator into emitting the corresponding opcodes.  Comments on
-- each line denote which opcode(s) should be generated by a typical
-- Lua 5.2 compiler.

local u1, u2, u3                    -- upvalue placeholders

-- define a function to encapsulate various operations
local function f1(a1, a2, ...)
    -- basic moves and constants
    local l0 = a1                    -- MOVE
    local l1 = 1                     -- LOADK
    local l2 = true                  -- LOADBOOL
    local l3 = nil                   -- LOADNIL
    -- global access goes through _ENV (gettabup/settabup)
    local env = _ENV                  -- GETTABUP for _ENV
    local g = env["print"]          -- GETTABUP (load a global)
    env["dummy"] = g                -- SETTABUP
    -- upvalue access
    l2 = u2                          -- GETUPVAL
    u2 = l2                          -- SETUPVAL
    -- table indexing and update
    local l4 = l3[l2]                -- GETTABLE
    l3[l2] = l1                      -- SETTABLE
    -- new table and setlist
    local t = { l1, l2; x = l2 }     -- NEWTABLE / SETLIST / SETTABLE
    -- self/method call
    local l6 = t:x()                 -- SELF / CALL
    -- arithmetic expressions exercising ADD, SUB, MUL, DIV, MOD, POW and UNM
    local l7 = -((l0 + l1 - l2) * l3 / (#t or 1) % l1)^l6
    -- boolean negation and length
    local l8 = #(not l7)             -- NOT, LEN
    -- concatenation
    local l9 = tostring(l7) .. tostring(l8)  -- CONCAT
    -- comparisons and jumps
    if l1 == l2 and l2 < l3 or l3 <= l4 then -- EQ, LT, LE, JMP
        -- numeric for‑loop (FORPREP/FORLOOP)
        for i = 1, 5, 2 do
            l0 = l0 and l2          -- TEST (checks truthiness)
        end
    else
        -- generic for‑loop over ipairs (TFORCALL/TFORLOOP)
        for k, v in ipairs(t) do
            l4 = l4 or l6           -- TESTSET (stores if truthy, else jump)
        end
    end
    -- vararg handling and closure
    do
        local v1, v2 = ...          -- VARARG
        local function inner()       -- CLOSURE
            return v1, v2           -- RETURN
        end
        inner()                      -- CALL
    end
    -- return values / tailcalls
    return f1                       -- RETURN / TAILCALL
end

-- exercise return and tail call
return f1(0)